import { v4 as uuidv4 } from 'uuid';

const AiTool = [
  {
    id: uuidv4(),
    image: 'images/Grammer correction.svg',
    title: 'Grammar Correction',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'correction',
    link: '/aitools/correction',
    desc: 'This tool corrects sentences into standard English.',
  },
  // {
  //   "id": 47,
  //   "image": "images/Language.svg",
  //   "title": "Eng to other languages",
  //   "category": "AI Tools",
  //   "categorysty": "dec",
  //   "type": "languageConvertion",
  //   "link": "/engToOtherLanguages/languageConvertion",
  //   "desc": "Translates English into French, Spanish, and Japanese."
  // },
  {
    id: uuidv4(),
    image: 'images/Q & A.svg',
    title: 'Q & A',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'qa',
    link: '/aitools/qa',
    desc: 'Answer questions based on existing knowledge.',
  },
  {
    id: uuidv4(),
    image: 'images/summarize.svg',
    title: 'Summarize For 2nd Grader',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'summarize',
    link: '/aitools/summarize',
    desc: 'Translates difficult text into simpler concepts.',
  },
  {
    id: uuidv4(),
    image: 'images/movie to emoji.svg',
    title: 'Movie To Emoji',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'movieEmoji',
    link: '/aitools/movieEmoji',
    desc: 'Convert movie titles into emoji.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Keywords',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'keywordsExtract',
    link: '/aitools/keywordsExtract',
    desc: 'Extract keywords from a block of text.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Friend Chat',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'friendChat',
    link: '/aitools/friendChat',
    desc: 'Emulate a text message conversation.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Study Notes',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'studyNotes',
    link: '/aitools/studyNotes',
    desc: 'Provide a topic and get study notes.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Interview Questions',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'interviewQuestions',
    link: '/aitools/interviewQuestions',
    desc: 'Create interview questions.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Chat With AI',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'chatWithAi',
    link: '/aitools/chatWithAi',
    desc: 'Open ended conversation with an AI assistant.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Turn By Turn Directions',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'turnByTurnDirections',
    link: '/aitools/turnByTurnDirections',
    desc: 'Convert natural language to turn-by-turn directions.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Essay Outline',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'essayOutline',
    link: '/aitools/essayOutline',
    desc: 'Generate an outline for a research topic.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Notes To Summary',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'notesToSummary',
    link: '/aitools/notesToSummary',
    desc: 'Turn meeting notes into a summary.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Analogy Maker',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'analogyMaker',
    link: '/aitools/analogyMaker',
    desc: 'Create analogies of phrases.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Classification',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'classification',
    link: '/aitools/classification',
    desc: 'Classify items into categories via example.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Third Person Converter',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'thirdPersonConverter',
    link: '/aitools/thirdPersonConverter',
    desc: 'Converts first-person POV to the third-person.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Explain Code',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'explainCode',
    link: '/aitools/explainCode',
    desc: 'Explain a complicated piece of code.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Tweets Sentiment Classifier',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'tweetSentimentClassifie',
    link: '/aitools/tweetSentimentClassifie',
    desc: 'Classify tweets sentiment , by inputing tweets.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Recipe Maker From Ingredients',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'recipeMakerByIngredients',
    link: '/aitools/recipeMakerByIngredients',
    desc: 'Create a recipe from a list of ingredients.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Micro Horror Story',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'microHorrorStoryMaker',
    link: '/aitools/microHorrorStoryMaker',
    desc: 'Creates two to three sentence short horror stories from a topic input.',
  },
  // {
  //   "id": 66,
  //   "image": "images/keyword selection.svg",
  //   "title": "Python To Natural Language",
  //   "category": "AI Tools",
  //   "categorysty": "dec",
  //   "type": "pythonToNaturalLanguage",
  //   "link": "/aitools/pythonToNaturalLanguage",
  //   "desc": "Explain a piece of Python code in human understandable language."
  // },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Factual Answering',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'factualAnswering',
    link: '/aitools/factualAnswering',
    desc: "Guide the model towards factual answering by showing it how to respond to questions that fall outside its knowledge base. Using a '?' to indicate a response to words and phrases that it doesn't know provides a natural response that seems to work better than more abstract replies.",
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Javascript Helper Chatbot',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'javascriptHelperChatbot',
    link: '/aitools/javascriptHelperChatbot',
    desc: 'This is a message-style chatbot that can answer questions about using JavaScript.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Science Fiction Books List Maker',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'scienceFictionbooksListMaker',
    link: '/aitools/scienceFictionbooksListMaker',
    desc: 'Insert amount input upto 5 and this will makes a list of science fiction books.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Text Description To Color',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'textDescriptionToColor',
    link: '/aitools/textDescriptionToColor',
    desc: 'Turn a text description into a color.',
  },
  // {
  //   "id": 71,
  //   "image": "images/keyword selection.svg",
  //   "title": "JavaScript To Python",
  //   "category": "AI Tools",
  //   "categorysty": "dec",
  //   "type": "javascriptToPython",
  //   "link": "/aitools/javascriptToPython",
  //   "desc": "Convert simple JavaScript expressions into Python."
  // },
  // {
  //   "id": 72,
  //   "image": "images/keyword selection.svg",
  //   "title": "JavaScript One Line Function",
  //   "category": "AI Tools",
  //   "categorysty": "dec",
  //   "type": "javascriptOneLinerFunctionConverter",
  //   "link": "/aitools/javascriptOneLinerFunctionConverter",
  //   "desc": "Turn a JavaScript function into a one liner."
  // },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Summarization',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'tldrSummarization',
    link: '/aitools/tldrSummarization',
    desc: 'Summarize the text.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Ad From Product Description',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'adFromProductDescription',
    link: '/aitools/adFromProductDescription',
    desc: 'Turn a product description into ad copy.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'ESRB Rating',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'esrbTextRating',
    link: '/aitools/esrbTextRating',
    desc: 'Categorize text based upon ESRB ratings.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Marv The Sarcastic Chatbot',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'marvTheSarcasticChatbot',
    link: '/aitools/marvTheSarcasticChatbot',
    desc: 'Marv is a factual chatbot that is also sarcastic.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Calculate Time Complexity',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'calculateTimeComplexity',
    link: '/aitools/calculateTimeComplexity',
    desc: 'Find the time complexity of a function.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Python Bug Fixer',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'pythonBugfixer',
    link: '/aitools/pythonBugfixer',
    desc: ' Add an input if the source code is buggy, and then ask codex to generate a fixed code.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'SQL Request',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'createSqlQueries',
    link: '/aitools/createSqlQueries',
    desc: ' Create a simple SQL queries.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'ML/AI Language Model Tutor',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'mlAiLanguageModelTutor',
    link: '/aitools/mlAiLanguageModelTutor',
    desc: ' This is a QA-style chatbot that answers questions about language models.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Extract Contact Information',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'extractContactInformation',
    link: '/aitools/extractContactInformation',
    desc: 'Extract contact information from a block of text.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Restaurant Review Creator',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'restaurantReviewCreator',
    link: '/aitools/restaurantReviewCreator',
    desc: 'Turn a few words into a restaurant review.',
  },
  // {
  //   "id": 83,
  //   "image": "images/keyword selection.svg",
  //   "title": "Write A Python Docstring",
  //   "category": "AI Tools",
  //   "categorysty": "dec",
  //   "type": "writePythonDocString",
  //   "link": "/aitools/writePythonDocString",
  //   "desc": "Generate python docstring by simply input code."
  // },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Airport Code Extractor',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'airportCodeExtractor',
    link: '/aitools/airportCodeExtractor',
    desc: 'A simple prompt for extracting airport codes from text.',
  },
  // {
  //   "id": 87,
  //   "image": "images/keyword selection.svg",
  //   "title": "Spreadsheet Creator",
  //   "category": "AI Tools",
  //   "categorysty": "dec",
  //   "type": "spreadsheetCreator",
  //   "link": "/spreadsheet/spreadsheetCreator",
  //   "desc": "Create a spreadsheet by specifying columns and and data in those columns also specify format of spreading data \n eg : For movies \n movie name | release data | ratings  "
  // },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'VR Fitness Idea Generator',
    category: 'AI Tools',
    categorysty: 'dec',
    type: 'vrFitnessIdeaGenerator',
    link: '/aitools/vrFitnessIdeaGenerator',
    desc: 'Enter amount and get  ideas for fitness and virtual reality games upto 5.',
  },
  // {
  //   "id": 89,
  //   "image": "images/keyword selection.svg",
  //   "title": "Translate Programming Languages",
  //   "category": "AI Tools",
  //   "categorysty": "dec",
  //   "type": "translateProgrammingLanguages",
  //   "link": "/tanslateProgrammingLanguages/translateProgrammingLanguages",
  //   "desc": "Translate one programming language into another programming language"
  // }
];
export default AiTool;
