import { v4 as uuidv4 } from 'uuid';
const conversionToolsDb = [
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Currency Conversion',
    category: 'Conversion Tools',
    categorysty: 'dec',
    type: 'currencyConversion',
    link: '/conversiontools/currencyConversion',
    desc: 'Convert any of currency into your favourite currency.',
  },

  // {
  //   id: uuidv4(),
  //   image: 'images/keyword selection.svg',
  //   title: 'Text To PDF File',
  //   category: 'Conversion Tools',
  //   categorysty: 'dec',
  //   type: 'textToPdfFile',
  //   link: '/conversiontools/textToPdfFile',
  //   desc: 'Convert text to PDF and download the document.',
  // },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Temperature Conversion',
    category: 'Conversion Tools',
    categorysty: 'dec',
    type: 'temperatureConversion',
    link: '/conversiontools/temperatureConversion',
    desc: 'Convert any of temperature unit into your favourite units.',
  },

  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Pressure Conversion',
    category: 'Conversion Tools',
    categorysty: 'dec',
    type: 'pressureConversion',
    link: '/conversiontools/pressureConversion',
    desc: 'Convert any of pressure unit into your favourite units.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Volume Conversion',
    category: 'Conversion Tools',
    categorysty: 'dec',
    type: 'volumeConversion',
    link: '/conversiontools/volumeConversion',
    desc: 'Convert any of volume unit into your favourite units.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Area Conversion',
    category: 'Conversion Tools',
    categorysty: 'dec',
    type: 'areaConversion',
    link: '/conversiontools/areaConversion',
    desc: 'Convert any of area unit into your favourite units.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Time Conversion',
    category: 'Conversion Tools',
    categorysty: 'dec',
    type: 'timeConversion',
    link: '/conversiontools/timeConversion',
    desc: 'Convert any of time unit into your favourite units.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Mass Conversion',
    category: 'Conversion Tools',
    categorysty: 'dec',
    type: 'massConversion',
    link: '/conversiontools/massConversion',
    desc: 'Convert any of mass unit into your favourite units.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Power Conversion',
    category: 'Conversion Tools',
    categorysty: 'dec',
    type: 'powerConversion',
    link: '/conversiontools/powerConversion',
    desc: 'Convert any of power unit into your favourite units.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Length Conversion',
    category: 'Conversion Tools',
    categorysty: 'dec',
    type: 'lengthConversion',
    link: '/conversiontools/lengthConversion',
    desc: 'Convert any of length unit into your favourite units.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Speed Units Conversion',
    category: 'Conversion Tools',
    categorysty: 'dec',
    type: 'speedConversion',
    link: '/conversiontools/speedConversion',
    desc: 'Convert any of speed unit into your favourite units.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Fuel Economy Conversion',
    category: 'Conversion Tools',
    categorysty: 'dec',
    type: 'fuelEconomyConversion',
    link: '/conversiontools/fuelEconomyConversion',
    desc: 'Check fuel economy in different options.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Energy Conversion',
    category: 'Conversion Tools',
    categorysty: 'dec',
    type: 'energyConversion',
    link: '/conversiontools/energyConversion',
    desc: 'Convert any of energy unit into your favourite units.',
  },
  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Plane Angle Conversion',
    category: 'Conversion Tools',
    categorysty: 'dec',
    type: 'planeAngleConversion',
    link: '/conversiontools/planeAngleConversion',
    desc: 'Convert any of plane angle unit into your favourite units.',
  },

  {
    id: uuidv4(),
    image: 'images/keyword selection.svg',
    title: 'Data Storage Units',
    category: 'Conversion Tools',
    categorysty: 'dec',
    type: 'bitByteConversion',
    link: '/conversiontools/bitByteConversion',
    desc: 'Convert any of data storage unit into your favourite units.',
  },
];

export default conversionToolsDb;
