import { v4 as uuidv4 } from 'uuid';
const CssTool = [
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Minify Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/minify-css',
    desc: 'Generate CSS Minify with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Formatter Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/css-formatter',
    desc: 'Generate CSS Formatter with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Box Shadow Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/box-shadow',
    desc: 'Generate Box Shadow with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/card-icon-21.png',
    title: 'CSS Gradient Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/gradient',
    desc: 'Generate CSS gradient with our CSS generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Text Shadow Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/text-shadow',
    desc: 'Generate Text Shadow with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Columns Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/column-gen',
    desc: 'Generate Columns with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Display Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/display-gen',
    desc: 'Generate CSS display with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Visibility Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/visibilty-gen',
    desc: 'Generate CSS Visibility with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Border Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/border-gen',
    desc: 'Generate CSS Border with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Border Radius Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/border-radius-gen',
    desc: 'Generate CSS border radius with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Transform Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/transform-gen',
    desc: 'Generate CSS Transform with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Border Image Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/border-img-gen',
    desc: 'Generate CSS Border Image with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Box Resize Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/box-resize-gen',
    desc: 'Generate CSS box resize with our CSS generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Opacity Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/opacity-gen',
    desc: 'Generate CSS Opacity with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Outline Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/outline-gen',
    desc: 'Generate CSS outline with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Overflow Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/overflow-gen',
    desc: 'Generate CSS Overflow with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Background Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/background-gen',
    desc: 'Generate CSS Background with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Text Color Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/text-color-gen',
    desc: 'Generate CSS text color with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Blur Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/blur-gen',
    desc: 'Generate CSS Blur with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Brightness Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/brightness-gen',
    desc: 'Generate CSS brightness with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Contrast Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/contrast-gen',
    desc: 'Generate CSS Contrast with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Grayscale Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/grayscale-gen',
    desc: 'Generate CSS Grayscale with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Hue Rotate Generator ',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/hue-rotate',
    desc: 'Generate CSS Hue Rotate with our CSS generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Invert Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/invert-gen',
    desc: 'Generate CSS Invert with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Saturate Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/saturate-gen',
    desc: 'Generate CSS Saturate with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Sepia Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/sepia-gen',
    desc: 'Generate CSS Sepia with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS List Style Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/list-style-gen',
    desc: 'Generate CSS List Style with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Cursor Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/cursor',
    desc: 'Generate CSS Cursor with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Letter Spacing Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/letter-spacing',
    desc: 'Generate CSS Letter Spacing with our generator tool.',
  },

  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Text Align Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/align-text',
    desc: 'Generate CSS Align Text with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Text Decoration Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/text-decoration',
    desc: 'Generate CSS Text Decoration with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Text Indent Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/indent-text',
    desc: 'Generate CSS Indent with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Text Transform Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/transform-text',
    desc: 'Generate CSS Transform with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS White Space Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/whitespace',
    desc: 'Generate CSS White Space with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Word Break Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/break-word',
    desc: 'Generate CSS Word Break with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Word Spacing Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/word-spacing',
    desc: 'Generate CSS Word Spacing with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Line Height Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/line-height',
    desc: 'Generate CSS Line Height with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Overflow Wrap Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/overflow-wrap',
    desc: 'Generate CSS Overflow wrap with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Tab Size',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/tab-size-gen',
    desc: 'generate Tab sizes',
  },
];
export default CssTool;
