import { v4 as uuidv4 } from 'uuid';
const HtmlTool = [
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Minify Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-minify',
    desc: 'Generate HTML Minify with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Formatter',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-formatter',
    desc: 'HTML Formatter with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Image Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-image-gen',
    desc: 'Generate HTML Image with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Iframe Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-ifram-gen',
    desc: 'Generate HTML Iframe with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Link Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-link-gen',
    desc: 'Generate HTML Link with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Button Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-button-gen',
    desc: 'Generate HTML Button with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Color Input Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-color_input-gen',
    desc: 'Generate HTML Color Input with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Date Input Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-date_input-gen',
    desc: 'Generate HTML Date Input with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Email Input Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-email_input-gen',
    desc: 'Generate HTML Email Input with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML File Input Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-file_input-gen',
    desc: 'Generate HTML File Input with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Image Input Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-image_input-gen',
    desc: 'Generate HTML Image Input with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Number Input Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-number_input-gen',
    desc: 'Generate HTML Number Input with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Password Input Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-password_input-gen',
    desc: 'Generate HTML Password Input with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Range Input Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-range_input-gen',
    desc: 'Generate HTML Range Input with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Search Input Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-search_input-gen',
    desc: 'Generate HTML Search Input with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Submit Input Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-submit_input-gen',
    desc: 'Generate HTML Submit Input with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Telephone Input Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-telephone_input-gen',
    desc: 'Generate HTML Telephone Input with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Text Input Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-text_input-gen',
    desc: 'Generate HTML Text Input Generator with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML URL Input Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-url_input-gen',
    desc: 'Generate HTML URL Input with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Text Area Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-textarea-gen',
    desc: 'Generate HTML Text Area with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Audio Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-audio-gen',
    desc: 'Generate HTML Audio with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Video Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-video-gen',
    desc: 'Generate HTML Video with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Bi Directional Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-bi-directional-gen',
    desc: 'Generate HTML Bi Directional with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Bold Generator ',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-bold-gen',
    desc: 'Generate HTML Bold with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Citation Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-cite-gen',
    desc: 'Generate HTML Citation with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Code Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-code-gen',
    desc: 'Generate HTML Code with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Italic Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-italic-gen',
    desc: 'Generate HTML Italic with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Highlight  Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-highlight-gen',
    desc: 'Generate HTML Highlight with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Strikethrough Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-strikethrough-gen',
    desc: 'Generate HTML Strikethrough with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Underline Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-underline-gen',
    desc: 'Generate HTML Underline with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Quote & Blockquote Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-quote-gen',
    desc: 'Generate HTML Quote & Blockquote with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Superscript & Subscript Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-superscript-gen',
    desc: 'Generate HTML Superscript & Subscript with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Details Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-detail-gen',
    desc: 'Generate HTML Details with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Meter Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-meter-gen',
    desc: 'Generate HTML Meter with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/html-file.png',
    title: 'HTML Progress Bar Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-progress-gen',
    desc: 'Generate HTML Progress Bar with our generator tool.',
  },
];
export default HtmlTool;
