import { v4 as uuidv4 } from 'uuid';
const JsonTool = [
  {
    id: uuidv4(),
    image: 'images/json-file.png',
    title: 'JSON Minify Generator',
    category: 'JSON Tools',
    categorysty: 'dec',
    type: '',
    link: '/json/minify-json',
    desc: 'Generate JSON Minify with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/json-file.png',
    title: 'JSON Formatter',
    category: 'JSON Tools',
    categorysty: 'dec',
    type: '',
    link: '/json/json-formatter',
    desc: 'Formate JSON Formatter with our  generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/json-file.png',
    title: 'JSON Validator',
    category: 'JSON Tools',
    categorysty: 'dec',
    type: '',
    link: '/json/json-validator',
    desc: 'Validate Json with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/json-file.png',
    title: 'JSON To XML Generator',
    category: 'JSON Tools',
    categorysty: 'dec',
    type: '',
    link: '/json/json-to-xml',
    desc: 'Generate JSON To XML with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/json-file.png',
    title: 'XML To JSON Generator',
    category: 'JSON Tools',
    categorysty: 'dec',
    type: '',
    link: '/json/xml-to-json',
    desc: 'Generate XML To JSON with our  generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/json-file.png',
    title: 'JSON To YAML Generator',
    category: 'JSON Tools',
    categorysty: 'dec',
    type: '',
    link: '/json/json-to-yaml',
    desc: 'Generate JSON To YAML with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/json-file.png',
    title: 'JSON To Base64 Generator',
    category: 'JSON Tools',
    categorysty: 'dec',
    type: '',
    link: '/json/json-to-base64',
    desc: 'Generate JSON To Base64 with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/json-file.png',
    title: 'Base64 To JSON Generator',
    category: 'JSON Tools',
    categorysty: 'dec',
    type: '',
    link: '/json/base64-to-json',
    desc: 'Generate Base64 To JSON with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/json-file.png',
    title: 'JSON To Text Generator',
    category: 'JSON Tools',
    categorysty: 'dec',
    type: '',
    link: '/json/json-to-text',
    desc: 'Generate JSON To Text with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/json-file.png',
    title: 'JSON To CSV Generator',
    category: 'JSON Tools',
    categorysty: 'dec',
    type: '',
    link: '/json/json-to-csv',
    desc: 'Generate JSON To CSV with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/json-file.png',
    title: 'CSV To JSON Generator',
    category: 'JSON Tools',
    categorysty: 'dec',
    type: '',
    link: '/json/csv-to-json',
    desc: 'Generate CSV To JSON with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/json-file.png',
    title: 'TSV To JSON Generator',
    category: 'JSON Tools',
    categorysty: 'dec',
    type: '',
    link: '/json/tsv-to-json',
    desc: 'Generate TSV To JSON with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/json-file.png',
    title: 'JSON To TSV Generator',
    category: 'JSON Tools',
    categorysty: 'dec',
    type: '',
    link: '/json/json-to-tsv',
    desc: 'Generate JSON To TSV with our generator tool.',
  },
];
export default JsonTool;
